# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmd.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmd.proto',
  package='alpd',
  syntax='proto3',
  serialized_options=b'Z\rprotos;protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tcmd.proto\x12\x04\x61lpd\"O\n\nCmdRequest\x12%\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x14.alpd.RequestContext\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t\"3\n\x0eRequestContext\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x13\n\x0bremote_addr\x18\x02 \x01(\t\"\x18\n\x08\x43mdReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2H\n\x0e\x43ommandService\x12\x36\n\x10\x45xecuteCommandV1\x12\x10.alpd.CmdRequest\x1a\x0e.alpd.CmdReply\"\x00\x42\x0fZ\rprotos;protosb\x06proto3'
)




_CMDREQUEST = _descriptor.Descriptor(
  name='CmdRequest',
  full_name='alpd.CmdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='alpd.CmdRequest.context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='alpd.CmdRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args', full_name='alpd.CmdRequest.args', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=98,
)


_REQUESTCONTEXT = _descriptor.Descriptor(
  name='RequestContext',
  full_name='alpd.RequestContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='alpd.RequestContext.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remote_addr', full_name='alpd.RequestContext.remote_addr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=151,
)


_CMDREPLY = _descriptor.Descriptor(
  name='CmdReply',
  full_name='alpd.CmdReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='alpd.CmdReply.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=177,
)

_CMDREQUEST.fields_by_name['context'].message_type = _REQUESTCONTEXT
DESCRIPTOR.message_types_by_name['CmdRequest'] = _CMDREQUEST
DESCRIPTOR.message_types_by_name['RequestContext'] = _REQUESTCONTEXT
DESCRIPTOR.message_types_by_name['CmdReply'] = _CMDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CmdRequest = _reflection.GeneratedProtocolMessageType('CmdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CMDREQUEST,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:alpd.CmdRequest)
  })
_sym_db.RegisterMessage(CmdRequest)

RequestContext = _reflection.GeneratedProtocolMessageType('RequestContext', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCONTEXT,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:alpd.RequestContext)
  })
_sym_db.RegisterMessage(RequestContext)

CmdReply = _reflection.GeneratedProtocolMessageType('CmdReply', (_message.Message,), {
  'DESCRIPTOR' : _CMDREPLY,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:alpd.CmdReply)
  })
_sym_db.RegisterMessage(CmdReply)


DESCRIPTOR._options = None

_COMMANDSERVICE = _descriptor.ServiceDescriptor(
  name='CommandService',
  full_name='alpd.CommandService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=179,
  serialized_end=251,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExecuteCommandV1',
    full_name='alpd.CommandService.ExecuteCommandV1',
    index=0,
    containing_service=None,
    input_type=_CMDREQUEST,
    output_type=_CMDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMANDSERVICE)

DESCRIPTOR.services_by_name['CommandService'] = _COMMANDSERVICE

# @@protoc_insertion_point(module_scope)
