apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpd-bot-auth-${USER}-deployment
spec:
  selector:
    matchLabels:
      app: alpd-bot-auth-${USER}
  replicas: 1
  template:
    metadata:
      labels:
        app: alpd-bot-auth-${USER}
    spec:
      containers:
      - name: alpd-bot-auth-${USER}
        image: ${DOCKER_IMAGE}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: alpd-bot-auth-${USER}-svc
spec:
  selector:
    app: alpd-bot-auth-${USER}
  ports:
    - name: grpc
      protocol: TCP
      port: 9001
      targetPort: 9001
