apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpd-bot-auth-deployment
spec:
  selector:
    matchLabels:
      app: alpd-bot-auth
  replicas: 1
  template:
    metadata:
      labels:
        app: alpd-bot-auth
    spec:
      containers:
      - name: alpd-bot-auth
        image: alpd-bot-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: alpd-bot-auth-svc
spec:
  selector:
    app: alpd-bot-auth
  ports:
    - name: grpc
      protocol: TCP
      port: 9001
      targetPort: 9001
