apiVersion: v1
kind: ConfigMap
metadata:
  name: albotssh-local-k8s
  namespace: default
data:
  local-k8s: |
    {
      "port": "2222",
      "authAddr": "alpd-bot-auth-svc:9001",
      "authTimeout": 2000,
      "execAddr": "alpd-bot-query-svc:9099",
      "execTimeout": 5000,
      "hostKeyFile": "/id_rsa"
    }
